spring:
  application:
    name: currency-fallback-service

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

external:
  rates:
    base-url: https://open.er-api.com
    latest-path: /v6/latest/
    base-currency: USD
